### ISSUE TITLE
Menu doesn't match demo

### ISSUE THREAD

**Issue by N6REJ** [gsuez/MasterBootswatch#2]
I pulled git, zipped and installed in working site and the menu does not function properly.
following the documentation and matching to your demo site does not work.
How do we get the menu to function properly?
![capture](https://cloud.githubusercontent.com/assets/1850089/7777859/fe5de12c-008b-11e5-8aaf-3b49d5488f65.JPG)

**Comment by gsuez** [comment]
you have a live site? should work good, the demo site is the same as downloads... you checked the menu module classes?

**Comment by N6REJ** [comment]
yes, I tried in both module suffix and menu suffix, even set the class's manually via element inspector.
I don't have a live site yet but I can put one up for you in a minute... one second while I do so.

**Comment by N6REJ** [comment]
please see http://genesis.jowwow.net/  I'll pm you the admin info via skype.

**Comment by htmgarcia** [comment]
@N6REJ there is a jquery issue that possibily is messing the menu.

This come up with Firebug addon > Console enabled:

```
ReferenceError: jQuery is not defined
})(jQuery);
```

Checking source code, your site is actually not loading jQuery

**Comment by N6REJ** [comment]
thats interesting cause it is j! 3.4.1 and bootswatch... let me try in staging install and see what happens....

**Comment by gsuez** [comment]
@N6REJ you site no call js/jui folder... check this issue

**Comment by N6REJ** [comment]
@htmgarcia nice catch.. in staging it loads the js but doesn't display properly if I put 
navbar navbar-default navbar-fixed-top in either menu suffix or module suffix.
![capture](https://cloud.githubusercontent.com/assets/1850089/7799832/2c8aadc2-02d1-11e5-948e-2c9911d28635.JPG)
what am I missing?  I'll reinstall joomla on the sandbox and see if It makes any difference, maybe I got a bad install since obviously the framework call is not functioning properly.
@gsuez  gratz on your joscar nomination, hope you win it as you've got a promising starting point here.

**Comment by htmgarcia** [comment]
@N6REJ what about trying jQuery easy plugin as alternative solution to load jQuery?

**Comment by N6REJ** [comment]
@htmgarcia i suppose but shouldn't be needed on a quickstart install if all plugins that are not core are removed... i'm digging to see what might be going on.... if it wasn't for how nice the quickstart content is for testing that ordasoft has I wouldn't even care about their content... but that doesn't solve the problem that I still can't get a horizontal bar, even on staging.. js loads but not horizontal menu.
http://ordasvit.com/ostemplate/ is the demo content I want to keep for a testing purpose

**Comment by N6REJ** [comment]
@gsuez @htmgarcia ok, i found the problem and partial cure...
the "module suffix" is never used.  the div for module call doesn't show up.
![1](https://cloud.githubusercontent.com/assets/1850089/7801181/2068a886-02e6-11e5-9b16-9b5e46c936cc.JPG) this is the "normal" behavior
and this is what happens...
![2](https://cloud.githubusercontent.com/assets/1850089/7801185/3833ccc0-02e6-11e5-950b-039f24bc94b5.JPG)

to fix the menu so it matches, you do infact NOT include navbar navbar-default navbar-fixed-top as indicated in the documentation as its already included in the mod_menu
![3](https://cloud.githubusercontent.com/assets/1850089/7801194/685ffa9a-02e6-11e5-9d5b-ea290d9a3535.JPG)
instead you must add  navbar-nav navbar-right to the MENU class suffix.
i tested this module class suffix problem by added "bob" as a suffix and it never showed up as you can see in the screen shots.

after making that change I get
![4](https://cloud.githubusercontent.com/assets/1850089/7801211/c900e1fc-02e6-11e5-8c28-df928919ee35.JPG)
as expected

**Comment by htmgarcia** [comment]
@N6REJ your site is still broken here: http://genesis.jowwow.net/

**Comment by N6REJ** [comment]
yeah, that site is, this is local... go here http://embryo.jowwow.net/ i've updated it with what I currently have on local

**Comment by gsuez** [comment]
Hey N6REJ, I fixed manual, now is ok. Regards

**Comment by N6REJ** [comment]
ok cool, glad I wasnt' wasting everyone times :)
